server:
  port: 8085
spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      properties:
        specific:
          avro:
            reader: true
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: LLHE5WEJND2NIQLR:e8ldl2VwQhD0U7wcpInMa8Loky8vCwDa3vANxENCiRysi0q4LBelLX7cid5NyVC/
      bootstrap:
        servers: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
      group:
        id: G1
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='F3SJVSPYJMDZDMMC' password='8pokBjax7TOID2i6RSTgi+QNdUBnUB2IlZXrtGt3OTbAFouflhqKG0rlXsVsfDu9';
        mechanism: PLAIN
      schema:
        registry:
          url: https://psrc-35wr2.us-central1.gcp.confluent.cloud
      security:
        protocol: SASL_SSL
      session:
        timeout:
          ms: 45000
topic: source